### ISSUE TITLE
Autocomplete object properties correctly

### ISSUE THREAD

**Issue by aqrln** [nodejs/node-inspect#31] opened 2017-03-09 23:49 UTC
Right now autocompletion of properties of an object works properly in Node's REPL and in in `node debug` but not in node-inspect.

**Comment by jkrems** [comment] 2017-03-10 18:46
Thanks! Reproduced via:

```
$ node cli.js examples/empty.js
# ... noise ...
debug> repl
Press Ctrl + C to leave debug repl
# Didn't work in `node debug` either:
> proc<tab>
# DID work in `node debug`:
> process.pi<tab>
```

**Comment by Delapouite** [comment] 2017-10-20 14:49
You're right, typing : 
`> process.pi<tab>`
does not work. Because the process.pid does not seem to be available in this context.

But : 
`> process.toS<tab>`
autocompletes `process.toString()` correctly.

So I guess that it's not really the autocomplete system which is broken, more the lack of accessible properties on `process`.

**Comment by davidjb** [comment] 2017-12-18 08:21
I've noticed the same thing as well.  The reason for the issue is that the object being autocompleted is a `RemoteObject` (https://github.com/nodejs/node-inspect/blob/master/lib/internal/inspect_repl.js#L150) rather than the original object itself.  This `RemoteObject` is created out of the [debugger's evaluation](https://github.com/nodejs/node-inspect/blob/master/lib/internal/inspect_repl.js#L498) and so in `node-inspect`, the properties shown (`type` and `value`) are those of the `RemoteObject` rather than the string:
```
$ node inspect 'empty.js'
debug> repl
Press Ctrl + C to leave debug repl
> foo = 'asdf'
'asdf'
> foo.<Tab><Tab>
foo.__defineGetter__      foo.__defineSetter__
foo.__lookupGetter__      foo.__lookupSetter__
foo.__proto__             foo.constructor
foo.hasOwnProperty        foo.isPrototypeOf
foo.propertyIsEnumerable  foo.toLocaleString
foo.toString              foo.valueOf

foo.type                  foo.value

> foo.__proto__
{ length: 0,
  constructor: ,
  charAt: ,
  charCodeAt: ,
  concat: ,
  ... }
```

By comparison, in `node`'s REPL itself, you can see all the various string properties:
```
$ node
> foo = 'asdf'
'asdf'
> foo.
foo.__defineGetter__      foo.__defineSetter__
foo.__lookupGetter__      foo.__lookupSetter__
foo.__proto__             foo.constructor
foo.hasOwnProperty        foo.isPrototypeOf
foo.propertyIsEnumerable  foo.toLocaleString
foo.toString              foo.valueOf

foo.anchor                foo.big
foo.blink                 foo.bold
foo.charAt                foo.charCodeAt
foo.codePointAt           foo.concat
foo.endsWith              foo.fixed
[...snip...]

> foo.__proto__
[String: '']
```

It seems that to fix the issue, either the `RemoteObject` needs to be made to _be_ the object itself, or else made to resemble it.  The current `node-inspect` code is similar in reconstituting something resembling the object [during formatting](https://github.com/nodejs/node-inspect/blob/master/lib/internal/inspect_repl.js#L157), which involves a lot of type/subtype checking. 

I don't know enough about the internals of Node or the REPL but hopefully there's a simpler fix than trying rebuild the object and its potential nested properties.

**Comment by jkrems** [comment] 2017-12-18 16:19
@davidjb That's a separate issue. `RemoteObject` didn't exist in the old debugger, so that's more a "missing feature" than a regression.

The reason why it needs to be a magic object instead of the "real" object is that it's in a separate process. The `repl` runs in the `node-inspect` process and the object lives in the debug target. Chrome's debug protocol has the concept of `RemoteObject` to allow the debug client to hold a reference to an object inside of the other process. Inside of Chrome Devtools UI this is used to allow you to inspect the "live" object state for example. It would be cool to make the same work in `node-inspect` but it's a non-trivial task to a) find a good/intuitive command line UI for this behavior and then b) make it actually work. ^^

**Comment by davidjb** [comment] 2017-12-19 01:31
@jkrems The original issue read as though it was referring to any given object, not just those in scope of the debugger.
> Right now autocompletion of properties of an object works properly in Node's REPL and in in node debug but not in node-inspect.

I could only go off what I was reading so I'll open another issue if you'd prefer to consider these issues separately.

In any case, as you say, it would be great if it could work to inspect the live object state.  As I found it, the current tab completion is confusing as it displays the `RemoteObject`'s properties and these don't apply to that real object.

**Comment by Trott** [comment] 2021-06-30 04:36
This has been dormant for over 3 years so I'm going to close it. However if it is still a desirable feature, open an issue in https://github.com/nodejs/node as that's where node-inspect now lives. This repository will be archived at some point in the not-too-distant future.

**Closed by Trott** 2021-06-30 04:36 UTC
